### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by OGViih** [uguraltinsoy/FCMSend#1]
Yoo thanks for this man , but you keep saying phone token ,or title body? Which I dont understand,  what if I want to send a notification to all users ,to all phones that have my app installed , pls help me

**Comment by uguraltinsoy** [comment]
The solution to the problem is very simple. First of all, all your devices are[ Subscribed to the Topic](https://github.com/uguraltinsoy/FCMSend#subscribe-to-topic) . Then[ send a notification to subscribers](https://github.com/uguraltinsoy/FCMSend#send-push-notifications-by-topic)

**Comment by OGViih** [comment]
> The solution to the problem is very simple. First of all, all your devices are[ Subscribed to the Topic](https://github.com/uguraltinsoy/FCMSend#subscribe-to-topic) . Then[ send a notification to subscribers](https://github.com/uguraltinsoy/FCMSend#send-push-notifications-by-topic)

Thanks mate ,I'll try it , pls where do I subscribe all users in the MainActivity or my  NotificationAcrivity

**Comment by uguraltinsoy** [comment]
Example:
Into MainActivity (LAUNCHER Activity)
Name : all_device
```Java
FirebaseMessaging.getInstance().subscribeToTopic("all_device").addOnSuccessListener(new OnSuccessListener<Void>() {  
	@Override  
	public void onSuccess(Void aVoid) {
		System.out.println("Subscription successful");
	}  
});
```
```KOTLIN
FirebaseMessaging.getInstance().subscribeToTopic("all_device").addOnSuccessListener {
	println("Subscription successful")
}
```

Send push notifications to after
```Java
FCMSend.Builder build = new FCMSend.Builder("all_device", true)
        .setTitle("<Title>")
        .setBody("<Message>");
String result = build.send().Result();
```
```KOTLIN
val build = FCMSend.Builder("all_device", true)
        .setTitle("<Title>")
        .setBody("<Message>")
val result = build.send().Result()
```
Just try

**Comment by OGViih** [comment]
> Example: Into MainActivity (LAUNCHER Activity) Name : all_device
> 
> ```java
> FirebaseMessaging.getInstance().subscribeToTopic("all_device").addOnSuccessListener(new OnSuccessListener<Void>() {  
> 	@Override  
> 	public void onSuccess(Void aVoid) {
> 		System.out.println("Subscription successful");
> 	}  
> });
> ```
> 
> ```kotlin
> FirebaseMessaging.getInstance().subscribeToTopic("all_device").addOnSuccessListener {
> 	println("Subscription successful")
> }
> ```
> 
> Send push notifications to after
> 
> ```java
> FCMSend.Builder build = new FCMSend.Builder("all_device", true)
>         .setTitle("<Title>")
>         .setBody("<Message>");
> String result = build.send().Result();
> ```
> 
> ```kotlin
> val build = FCMSend.Builder("all_device", true)
>         .setTitle("<Title>")
>         .setBody("<Message>")
> val result = build.send().Result()
> ```
> 
> Just try

Brother it  gave me an error when I use "true" boolean in the builder

**Comment by uguraltinsoy** [comment]
Which version are you using? You must use the latest version

```
implementation 'com.github.uguraltinsoy:FCMSend:1.0.2'
```

**Comment by OGViih** [comment]
> Which version are you using? You must use the latest version
> 
> ```
> implementation 'com.github.uguraltinsoy:FCMSend:1.0.2'
> ```

Lool thanks , bro do you know anyway ,I can make firebase send my cloud notifications instantly to my users because I send something and it takes minutes or even hours before my phone gets the notification
