### ISSUE TITLE
Sir Please tell me how we perform click function through this library

### ISSUE THREAD

**Issue by ApiXDoc** [uguraltinsoy/FCMSend#2]
sir notification works fine what when we click on notification noting is happened sir please tell me how we perform click function on notification

**Comment by uguraltinsoy** [comment]
You can check the section I updated and added the library.
https://github.com/uguraltinsoy/FCMSend#if-there-is-a-click-action

**Comment by ApiXDoc** [comment]
thanks to update the library but still, when we click on notification nothing is happening i just want when the user to click on notification its launch app particular activity

**Comment by uguraltinsoy** [comment]
Is your manifest file correct?

**Comment by ApiXDoc** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/112341110/187182333-599650c4-ea81-4b6a-89dc-761f47bcd0e4.png)

yes my manifest is correct

**Comment by uguraltinsoy** [comment]
I get notification but it doesn't open when I click it, right?

**Comment by ApiXDoc** [comment]
yes sir

**Comment by uguraltinsoy** [comment]
I'm not sure what the problem is, I added another version, can you try it too, but there seems to be a problem on your part.

**Comment by ApiXDoc** [comment]
thank you so much sir you help me a lot and your service class miss this line of code so click is not work i add these line and its work

 Intent intent=new Intent(getApplicationContext(), Splash.class);

        intent.putExtra("title",title);



        PendingIntent pendingIntent= PendingIntent.getActivity(
                getApplicationContext(),100,intent,PendingIntent.FLAG_CANCEL_CURRENT);


        NotificationCompat.Builder builder=

                new NotificationCompat.Builder(getApplicationContext(), investment_payment_act.CHANNEL_ID)
                        .setSmallIcon(R.mipmap.ic_launcher)
                        .setContentTitle(title)
                        .setContentIntent(pendingIntent)
                        .setContentText(text)
                        .setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
                        .setPriority(NotificationCompat.PRIORITY_DEFAULT);


        NotificationManagerCompat notificationManagerCompat= NotificationManagerCompat.from(getApplicationContext());

        notificationManagerCompat.notify(1,builder.build());
